added vmware player 2.5.1 2.6.29 patch, testing now.

diff --git a/svmi b/svmi
--- a/svmi
+++ b/svmi
@@ -2,8 +2,8 @@
 ########################################################################
 ####  Script Name: system virtual machine installer: svmi
 ####  Only use for Debian Sid, Testing and sidux, no support for any other distro
-####  version: 2.1.13
-####  Date: March 9 2009
+####  version: 2.2.0
+####  Date: March 31 2009
 ########################################################################
 ####  Copyright (C) Harald Hope 2007-2009
 ####  This program is free software; you can redistribute it and/or modify it under
@@ -244,6 +244,61 @@ fi
 ####  FUNCTIONS
 ########################################################################
 
+# args: $1 vbox/vmplayer
+apply_fixes_post_install()
+{
+	local i='' patchName='' patchUrl="$SCRIPT_DOWNLOAD/patches" dirData=''
+	
+	case $1 in
+		vbox)
+			:
+			;;
+		vmplayer)
+			case $KERNEL_THIRD in
+				29)
+					case $VMPLAYER_NUMBER in
+						2.5.1)
+							# patch logic: http://communities.vmware.com/thread/192355
+							# patch src: http://communities.vmware.com//message/1213099
+							# patch url:http://communities.vmware.com/servlet/JiveServlet/download/1213099-20834/vmware-modules-2.6.29.patch.gz  
+							echo $LINE
+							patchName='vmware-modules-2.6.29-2.5.1.patch'
+							patchUrl="$patchUrl/$patchName"
+							dirData='/usr/lib/vmware/modules/source/'
+							echo "${S}Retrieving patch for $VMPLAYER_NUMBER post install now...${N}"
+							wget -O $VMWARE_INSTALL_PATH/$patchName $patchUrl || error_handler 189
+							echo "${S}Preparing system for patching now...${N}"
+							if [ -d $dirData ];then
+								cd $dirData
+								mkdir orig
+								cp -f *.tar orig/
+								for i in $( ls *.tar )
+								do 
+									tar -xf $i
+								done
+								rm -f *.tar
+								echo "${S}Applying patch now...${N}"
+								patch -p1 -i $VMWARE_INSTALL_PATH/$patchName
+								echo "${S}Running post patch processes...${N}"
+								for i in mblock mci mmon mnet mppuser sock
+								do 
+									tar -cf v$i.tar v$i-only
+								done
+								rm -rf *-only
+								cd $SCRIPT_HOME # make sure to return to default
+								echo "${S}All done with patching operation, hope it works for you!${N}"
+							else
+								echo "${W}NO $dirData found, cannot proceed!!${N}"
+								print_hec
+							fi
+							;;
+					esac
+					;;
+			esac
+			;;
+	esac
+}
+
 # only for debugging purposes
 set_test_data()
 {
@@ -427,6 +482,9 @@ error_handler()
 			;;
 		190)
 			errorData="Unsupported testing option argument: -! $errorExtra"
+			;;
+		189)
+			errorData="Patching failed for $2"
 			;;
 		*)
 			errorData="Unexpected Error !"
@@ -1305,6 +1363,7 @@ install_vmware()
 			install_anyany
 			run_file
 		fi
+		apply_fixes_post_install 'vmplayer'
 	fi
 
 	eval $LOGPE
